---
apiVersion: v1
kind: Service
metadata:
  name: nau-web-app-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: roman
  ports:
  - port: 80
    targetPort: 80
    
    name: http